### ISSUE TITLE
How do I use plugins?

### ISSUE THREAD

**Issue by tomaskikutis** [otsaloma/catapult#19] opened 2023-04-04 15:39 UTC
I saw there are plugins in the codebase, but I couldn't find how to activate them. I'd be useful to add some tips to the launcher UI itself. I like how pop os launcher does it by displaying usage instructions on typing `?`

https://user-images.githubusercontent.com/2076953/229844912-6ccd2edc-caa4-4620-b0db-67b22a60498d.mp4

**Comment by otsaloma** [comment] 2023-04-04 19:33
I guess I could add `?`. Currently `:` works (the built-in commands all begin with `:`), F1 works and a mouse click at the edge of the window works. And what you're looking for is `:preferences`.

**Comment by otsaloma** [comment] 2023-04-04 22:09
Catapult doesn't genrally have any trigger keys, so you need unlearn whatever you learned using triggered launchers. While I can understand having such expectations, I'm not going document around what others are doing. I find triggers to be an awful UI concept, very undiscoverable and too much to type for anything commonly used. There's plenty of launchers with triggers out there and no need for me or anyone else to write any more.

The goal is to be close to natural language and obvious without any extras. There's probably some things that would benefit from documentation – Catapult is a young project and not popular, so not much has been added yet, but I strongly resent documentation as a solution to UI issues, it's rather the UI that should be fixed so that's it's obvious and usable immediately.

For example, the calculator, you just type in something like `1+2` and it should display `3`. If it doesn't work, you're probably lacking `qalc` and it's an installation/packaging issue. With the calculator, there's also some conversion syntax to figure out, e.g. `1 km to mi` works, `1 km in mi` doesn't (as intended), but I think that's something you figure out easily by trying and the syntax is very similar to e.g. Google search.

**Comment by tomaskikutis** [comment] 2023-04-05 08:22
I see you have a lot to say about trigger keys. :slightly_smiling_face: To me it seems it could be configurable and make everyone happy. On the other hand, if you run without trigger keys - you get into some performance and even privacy issues. If I type "8 mile" it might be a search engine query, file system search or a calculator conversion. Would all plugins run? I wouldn't like everything I type in the launcher to be sent to a search engine. Neither file system to start scanning which is performance intensive.

**Comment by otsaloma** [comment] 2023-04-05 20:19
> To me it seems it could be configurable and make everyone happy.

No.

Plugins can of course react to queries however they define, but I'm not here to make everyone happy and I'm not going to facilitate bad practises in the core plugins or UI.

> I wouldn't like everything I type in the launcher to be sent to a search engine. Neither file system to start scanning which is performance intensive.

I'm aware that some launchers have a large amount of website-specific plugins. That doesn't make much sense to me, neither from use nor maintenance point of view. You can consider it out of scope for Catapult. Anyone seeking to use or write such plugins can probably find a better launcher and plugin API elsewhere.

Catapult's file indexing plugin runs every time the launcher window is shown if N minutes (default 15) have passed since the last time the index was updated. It's not designed to scan your whole file system (why would you even want that?), but rather things like top-level project directories that you define (`~/Projects/*` etc.).

It would of course be possible to implement file indexing differently, such as using tracker – that's something that you can implement in a plugin if you like and use that instead. There's no filesystem scanning (as far as I know), just hitting some tracker database that might even be in memory.

**Closed** 2023-04-14 19:46 UTC
